vich_uploader:
    db_driver: orm

    mappings:
        intervenant_images:
            uri_prefix: '%app.path.intervenant_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.intervenant_images%'

        sponsor_images:
            uri_prefix: '%app.path.sponsor_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.sponsor_images%'

        postere_images:
            uri_prefix: '%app.path.postere_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.postere_images%'